/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index.route'
import { Route as TopicIndexRouteImport } from './routes/topic/index.route'
import { Route as SeriesIndexRouteImport } from './routes/series/index.route'
import { Route as TopicNewIndexRouteImport } from './routes/topic/new/index.route'
import { Route as TopicNameIndexRouteImport } from './routes/topic/$name/index.route'
import { Route as SeriesNewIndexRouteImport } from './routes/series/new/index.route'
import { Route as SeriesNameIndexRouteImport } from './routes/series/$name/index.route'

// Create/Update Routes

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TopicIndexRouteRoute = TopicIndexRouteImport.update({
  path: '/topic/',
  getParentRoute: () => rootRoute,
} as any)

const SeriesIndexRouteRoute = SeriesIndexRouteImport.update({
  path: '/series/',
  getParentRoute: () => rootRoute,
} as any)

const TopicNewIndexRouteRoute = TopicNewIndexRouteImport.update({
  path: '/topic/new/',
  getParentRoute: () => rootRoute,
} as any)

const TopicNameIndexRouteRoute = TopicNameIndexRouteImport.update({
  path: '/topic/$name/',
  getParentRoute: () => rootRoute,
} as any)

const SeriesNewIndexRouteRoute = SeriesNewIndexRouteImport.update({
  path: '/series/new/',
  getParentRoute: () => rootRoute,
} as any)

const SeriesNameIndexRouteRoute = SeriesNameIndexRouteImport.update({
  path: '/series/$name/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/topic/': {
      id: '/topic/'
      path: '/topic'
      fullPath: '/topic'
      preLoaderRoute: typeof TopicIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/series/$name/': {
      id: '/series/$name/'
      path: '/series/$name'
      fullPath: '/series/$name'
      preLoaderRoute: typeof SeriesNameIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/series/new/': {
      id: '/series/new/'
      path: '/series/new'
      fullPath: '/series/new'
      preLoaderRoute: typeof SeriesNewIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/topic/$name/': {
      id: '/topic/$name/'
      path: '/topic/$name'
      fullPath: '/topic/$name'
      preLoaderRoute: typeof TopicNameIndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/topic/new/': {
      id: '/topic/new/'
      path: '/topic/new'
      fullPath: '/topic/new'
      preLoaderRoute: typeof TopicNewIndexRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/series': typeof SeriesIndexRouteRoute
  '/topic': typeof TopicIndexRouteRoute
  '/series/$name': typeof SeriesNameIndexRouteRoute
  '/series/new': typeof SeriesNewIndexRouteRoute
  '/topic/$name': typeof TopicNameIndexRouteRoute
  '/topic/new': typeof TopicNewIndexRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/series': typeof SeriesIndexRouteRoute
  '/topic': typeof TopicIndexRouteRoute
  '/series/$name': typeof SeriesNameIndexRouteRoute
  '/series/new': typeof SeriesNewIndexRouteRoute
  '/topic/$name': typeof TopicNameIndexRouteRoute
  '/topic/new': typeof TopicNewIndexRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRouteRoute
  '/series/': typeof SeriesIndexRouteRoute
  '/topic/': typeof TopicIndexRouteRoute
  '/series/$name/': typeof SeriesNameIndexRouteRoute
  '/series/new/': typeof SeriesNewIndexRouteRoute
  '/topic/$name/': typeof TopicNameIndexRouteRoute
  '/topic/new/': typeof TopicNewIndexRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/series'
    | '/topic'
    | '/series/$name'
    | '/series/new'
    | '/topic/$name'
    | '/topic/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/series'
    | '/topic'
    | '/series/$name'
    | '/series/new'
    | '/topic/$name'
    | '/topic/new'
  id:
    | '__root__'
    | '/'
    | '/series/'
    | '/topic/'
    | '/series/$name/'
    | '/series/new/'
    | '/topic/$name/'
    | '/topic/new/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  SeriesIndexRouteRoute: typeof SeriesIndexRouteRoute
  TopicIndexRouteRoute: typeof TopicIndexRouteRoute
  SeriesNameIndexRouteRoute: typeof SeriesNameIndexRouteRoute
  SeriesNewIndexRouteRoute: typeof SeriesNewIndexRouteRoute
  TopicNameIndexRouteRoute: typeof TopicNameIndexRouteRoute
  TopicNewIndexRouteRoute: typeof TopicNewIndexRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  SeriesIndexRouteRoute: SeriesIndexRouteRoute,
  TopicIndexRouteRoute: TopicIndexRouteRoute,
  SeriesNameIndexRouteRoute: SeriesNameIndexRouteRoute,
  SeriesNewIndexRouteRoute: SeriesNewIndexRouteRoute,
  TopicNameIndexRouteRoute: TopicNameIndexRouteRoute,
  TopicNewIndexRouteRoute: TopicNewIndexRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/series/",
        "/topic/",
        "/series/$name/",
        "/series/new/",
        "/topic/$name/",
        "/topic/new/"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/series/": {
      "filePath": "series/index.route.tsx"
    },
    "/topic/": {
      "filePath": "topic/index.route.tsx"
    },
    "/series/$name/": {
      "filePath": "series/$name/index.route.tsx"
    },
    "/series/new/": {
      "filePath": "series/new/index.route.tsx"
    },
    "/topic/$name/": {
      "filePath": "topic/$name/index.route.tsx"
    },
    "/topic/new/": {
      "filePath": "topic/new/index.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
